### ISSUE TITLE
Matplotlib and multiprocessing: RuntimeError: In set_text: could not load glyph

### ISSUE THREAD

**Issue by ivalaginja** [spacetelescope/PASTIS#48]
I have run into an issue with using `matplotlib` with `multiprocess`. When I run `matrix_building_numerical.num_matrix_multiprocess()`, which gets called form `launchers/run_hicat.py` or `launchers/run_luvoir.py` (tested on commit `61cea5` on branch `dev-beyond-multiprocess`), I get the following error:
```
2020-09-01 12:13:09,119 - root - INFO - Calculating mean contrast in dark hole
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/ilaginja/repos/PASTIS/pastis/matrix_building_numerical.py", line 535, in _hicat_matrix_one_pair
    plt.savefig(os.path.join(resDir, 'OTE_images', opd_name + '.pdf'))
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/pyplot.py", line 716, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2082, in print_figure
    **kwargs)
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/backends/backend_pdf.py", line 2503, in print_pdf
    self.figure.draw(renderer)
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2645, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/image.py", line 159, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/axis.py", line 1206, in draw
    renderer)
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/axis.py", line 1151, in _get_tick_bboxes
    for tick in ticks if tick.label1.get_visible()],
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/axis.py", line 1151, in <listcomp>
    for tick in ticks if tick.label1.get_visible()],
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/text.py", line 890, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/text.py", line 291, in _get_layout
    ismath="TeX" if self.get_usetex() else False)
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/site-packages/matplotlib/backends/_backend_pdf_ps.py", line 62, in get_text_width_height_descent
    font.set_text(s, 0.0, flags=ft2font.LOAD_NO_HINTING)
RuntimeError: In set_text: could not load glyph
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ilaginja/repos/PASTIS/pastis/launchers/run_hicat.py", line 16, in <module>
    dir_run = num_matrix_multiprocess(instrument='HiCAT')
  File "/Users/ilaginja/repos/PASTIS/pastis/matrix_building_numerical.py", line 646, in num_matrix_multiprocess
    results = mypool.map(calculate_matrix_pair, product(np.arange(nb_seg), np.arange(nb_seg)))
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/ilaginja/miniconda3/envs/pastis-hicat/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
RuntimeError: In set_text: could not load glyph

Process finished with exit code 1
```

I have identified this as a problem with plotting the reference PSF before going into the multiple processes that build the matrix and also save their results with `plt.savefig()`. When I set `save=False` in [line 602](https://github.com/spacetelescope/PASTIS/blob/61cea53fbe3c6ebca741fd54e7c0b5726183a7c2/pastis/matrix_building_numerical.py#L602) of `matrix_building_numerical.num_matrix_multiprocess()` (again launching from `launchers/run_hicat.py` or `launchers/run_luvoir.py`), the problem goes away as I never save the reference PSF in that sub function in the first place, which is called before using `multiprocess`. So at least I know what introduced this problem, which came in with commit `1bdef7` (“move PSF plotting from analysis to matrix script”).

Note how this problem appears both for LUVOIR and HiCAT.

Googling this didn’t make me much smarter, I found a couple of links but none of these really explain the issue:
(1) https://github.com/matplotlib/matplotlib/issues/13723
(2) https://stackoverflow.com/questions/52489602/could-not-load-glyph-in-multiprocessing

I tried making a minimal working example, but since I needed to include one of the solutions I tried to make this work in the first place (see second to last line in this code block), I can’t really say this example represents my case truthfully:
```py
import functools
from itertools import product
import matplotlib.pyplot as plt
import multiprocessing
import numpy as np
import os


def first_func():
    # do stuff
    img = np.zeros([178, 178])
    plt.figure()
    plt.imshow(img)
    plt.savefig('testing/my_figure.pdf')
    plt.close()


def calculate_matrix_pair(always_this, a_tuple):
    # do more stuff
    print(a_tuple)
    whatevs = 6
    myresult = whatevs * always_this
    image = np.zeros([178, 178])
    plt.figure()
    plt.imshow(image)
    plt.savefig(f'testing/one_matrix_element{a_tuple}.pdf')
    plt.close()

    return myresult, a_tuple


def calculate_matrix():
    # also do stuff
    first_func()
    number = 37

    random_thing = 5
    partial_func = functools.partial(calculate_matrix_pair, random_thing)

    num_cpu = multiprocessing.cpu_count()
    num_core_per_process = 1
    num_processes = int(num_cpu // num_core_per_process)
    mypool = multiprocessing.Pool(num_processes)
    results = mypool.map(partial_func, product(np.arange(number), np.arange(number)))
    print(results)


if __name__ == '__main__':
    os.mkdir('testing')
    multiprocessing.set_start_method('forkserver’)    # I had to include this to make it work on my macOS Catalina 10.15.5
    calculate_matrix()
```

There were a couple of suggestions in the links above that I tried out:

- Adding `multiprocessing.set_start_method('forkserver’)` in `matrix_building_numerical.num_matrix_multiprocess()` in line 607, just before starting the different processes: This makes it work, but I am not sure how robust this is across different platforms?
- Adding `multiprocessing.set_start_method(‘spawn’)`  instead makes it work too, but I am not sure why, same like in the above point. Also, the [multiprocess documentation](https://docs.python.org/3/library/multiprocessing.html) claims that “spawn” is the default way to start a process on MacOS anyway?
- [This comment](https://github.com/matplotlib/matplotlib/issues/13723#issuecomment-496852582) is (1) suggested to explicitly set `matplotlib.use("agg”)` - the different matplotlib backends have been a problem with this repo before, so I tried it, but without success.
- I am running this in a conda env with matplotlib 3.1.0 installed. I tried updating matplotlib to see whether the problem persists, but `conda update matplotlib` doesn’t do anything, presumably because of conflicts with other packages, so that’s not an option.

As an intermediate fix, I will simply turn off the saving of the reference PSF. However, it would be good to solve this at some point. Maybe @mperrin would have some ideas about this?

**Comment by davidbourgeois** [comment]
I apply this:
```
log = logging.getLogger()
mplfm_logger = logging.getLogger('matplotlib.font_manager')
mplcb_logger = logging.getLogger('matplotlib.colorbar')
mplt_logger = logging.getLogger('matplotlib.ticker')   
mplbe_logger = logging.getLogger('matplotlib.backends')

mplfm_logger.setLevel(logging.WARNING)
mplcb_logger.setLevel(logging.WARNING)
mplt_logger.setLevel(logging.WARNING)
```
Don't solve problems, but we are not annoying.
